- name: Ensure that required modules for EC2 are installed
  pip:
    name: boto3

- name:  Gather information about DB instance
  ec2_instance_info:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    filters:
      "tag:Name": DB
  register: ec2_remote_facts

-  set_fact:
     db_ip: "{{ ec2_remote_facts | json_query('instances[*].private_ip_address') }} "

- name: Copy PMA config template
  template:
    src: pma.config.inc.php.j2
    dest: /etc/phpMyAdmin/config.inc.php
    owner: php-fpm
    group: php-fpm
    mode: 0644

- name: updating DB security group that only web server has access to db port
  ec2_group:
    name: "{{ db_security_group }}"
    description: DB EC2 security group
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: "{{ ansible_default_ipv4.address }} /32"
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name:  Gather information of WEB instance
  ec2_instance_info:
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    filters:
      "tag:Name": WEB
  register: ec2_remote_facts_web

-  set_fact:
     external_ip: "{{ ec2_remote_facts_web | json_query('instances[*].public_ip_address') }} "

- debug:
    msg: "For phpMyAdmin connecto to https://{{ external_ip[0] }}"
